---
driver:
  name: vagrant

driver_config:
  network:
    - ['private_network', {ip: '192.168.33.33'}]

provisioner:
  name: chef_solo
  data_bags_path: data_bags

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[hadoop_cluster::default]
    attributes:
